### ISSUE TITLE
Doesn't work on Server

### ISSUE THREAD

**Issue by SharkieTV** [PersonTheCat/OreStoneVariants#141] opened 2021-12-29 07:41 UTC
Trying to add it to my Better Minecraft Modpack and v7.0 and v7.1 doesn't work on Server

Issue - https://pastebin.com/6DUEx0gE

**Comment by PersonTheCat** [comment] 2021-12-29 14:20
I can pretty much guarantee there is no client code leak on the server side. However, I am aware of a couple platform compatibility issues that only affect the server side. There is an unpublished fix for compatibility with Sponge-based platforms and the mod simply does not work with Java 11+. 

Guys, I have to make this clear. Please do not share a partial crash report with no other details. I need the whole entire crash report, as well as diagnostics about your setup and what changed that caused this problem. And, if you really want this bug fixed soon, please consider reproducing the crash with fewer than 200 mods. **Next time, I will close the ticket with no comment and just mark it as insufficient.** 

I need
* The entire crash report. This crash report is missing the cause (which is the most important part), as well as other game diagnostics that I do need.
* Your OS version
* Your Forge version
* Your CatLib version (very important)
* Details about your server configuration (some hosts have modified platforms. will need to know if you're using one)
* Any configuration changes to OSV or other mods that OSV may depend on
* Ideally, a drastically smaller subset of mods to investigate

**Comment by SharkieTV** [comment] 2021-12-29 15:56
Just tested with just the latest version of OSV and CatLib and still a mod loading error.

- It gives no crash just the log of the instant fail - https://pastebin.com/QfUBATC2
- Windows 10
- Forge 36.2.22
- CatLib-Forge-1.6.jar
- I test it on my PC like I do with all my other serverpacks, install server with forge installer
- no changes
- just your 2 mods tested now

**Comment by SharkieTV** [comment] 2021-12-29 15:57
[crash-2021-12-29_23.52.49-fml.txt](https://github.com/PersonTheCat/OreStoneVariants/files/7789679/crash-2021-12-29_23.52.49-fml.txt)
Never mind the crash is here

**Comment by PersonTheCat** [comment] 2021-12-29 16:11
Okay, I gotcha. This is just a warning message, but it throws exceptions for all errors on the server side. It's just trying to make a backup, but the file isn't there yet (which can be ignored on the client side, but not for server admins). 

This is technically not a bug, but it is un-ergonomic. I'll just update the default behavior from CatLib in a day or so. In the meantime, just run the server from the client side and then copy all your configs over. Let me know if you try that and it does or does not work. I'll also update here when the new CatLib version is out.

**Comment by SharkieTV** [comment] 2021-12-29 16:16
Yeah seems to work when I use the Configs from the client side thanks.

**Comment by PersonTheCat** [comment] 2021-12-29 16:18
Thanks! I'll update CatLib to only throw exceptions based on your configured `errorLevel` in the CatLib config file. While I'm here, I can also take this opportunity to have it display multiple errors at a time on the server side like it does on the client side. Will work on that today.

**Comment by PersonTheCat** [comment] 2021-12-29 20:24
Hey, I've released an update to OSV to provide compatibility with Sponge servers, as well as an update to CatLib to update the warning behavior so it doesn't crash out of the box. Let me know if you try it and everything works for you. Will close this ticket later tomorrow, otherwise.

**Closed** 2021-12-31 07:18 UTC
Labels: Mod Compatibility, not a bug
