### ISSUE TITLE
Log spam with OSV + Create

### ISSUE THREAD

**Issue by ChiefLogan3010** [PersonTheCat/OreStoneVariants#133] opened 2021-08-28 16:25 UTC
Versions:
Forge - 36.2.0
Ore Stone Variants-6.2
flywheel-1.16-0.2.3
create-mc1.16.5_v0.3.2d

Log:
https://gist.github.com/ChiefLogan3010/e31a4a21b6f7b37a9edb832399873731

When in a world with OSV + Create, the log is spammed with "[Netty Local Client IO #0/ERROR]: Error adding element: Value 128 outside of range [0:64]". Have tested with each mod individually and I do not get the same error. Have also tested in a pack with only the mods stated above so I think it's definitely something to do with the cross compatability.

**Comment by PersonTheCat** [comment] 2021-08-28 16:37
This issue is technically a duplicate of #129, but that issue seems to have been closed, so I'll leave it open. 

Basically, Create support is out of date. They've replaced some of their stone types and updated their world generation code and so OSV is no longer automatically compatible. I will update the Create support in the next version, but that's likely still at least 3 weeks away.

To work around this issue in the meantime, edit the `config/osv/stone/create_x.hjson` files by setting `gen.size` to `64` instead of `128`.

**Comment by ChiefLogan3010** [comment] 2021-08-28 16:42
Thanks for the explanation, I had a look through the titles of previous issues before posting but didn't find anything relevant that mentioned create, so I missed #129

**Comment by PersonTheCat** [comment] 2021-09-22 20:14
Currently working on a fix for this, but it will take at least a few more weeks. The next update (7.0) will be pretty big because we're rebuilding on top of CatLib + Architectury.

**Comment by PersonTheCat** [comment] 2021-12-13 15:47
Underestimated the complexity of 7.0, but I believe this issue can finally be closed. Everything is working for me. Please give the update a try and let me know if you're still having issues.

**Closed by PersonTheCat** 2021-12-13 15:47 UTC
