### ISSUE TITLE
Ore Stone Variants has failed to load correctly

### ISSUE THREAD

**Issue by hzt-plays** [PersonTheCat/OreStoneVariants#148] opened 2022-01-26 05:04 UTC
[crash-2022-01-26_12.56.51-fml.txt](https://github.com/PersonTheCat/OreStoneVariants/files/7939052/crash-2022-01-26_12.56.51-fml.txt)

**Comment by PersonTheCat** [comment] 2022-01-26 05:37
Thanks. Looks like several things went wrong here all at once to cause this issue. I won't be able to reproduce it, so I need to take a little time to see if I can figure out another way to do this.

**Comment by hzt-plays** [comment] 2022-01-26 08:58
Oh it's okay, I just thought I'm doing something wrong. By the way, I'm using the better minecraft modpack. Thank you very much! :))

**Comment by PersonTheCat** [comment] 2022-01-28 20:20
Hey, @hzt-plays. I still haven't been able to come up with a true fix for this issue. I've added some synchronization code that should hopefully prevent the crash, but I just can't reproduce the issue in order to confirm it. Do you mind testing this for me? I'm not confident this will work, but a true fix might be pretty tough to work out. 

[OSV-Forge-7.5.1-remapped.zip](https://github.com/PersonTheCat/OreStoneVariants/files/7961633/OSV-Forge-7.5.1-remapped.zip)

**Comment by NoirCoding** [comment] 2022-01-29 01:59
Hello, I'm also having this issue with the better minecraft modpack, any updates?

**Comment by PersonTheCat** [comment] 2022-01-29 02:04
@NoirCoding see the most recent message from earlier today.

**Comment by NoirCoding** [comment] 2022-01-29 16:35
@PersonTheCat Ohh that file seemed to work alright, thanks.

**Comment by PersonTheCat** [comment] 2022-01-29 17:49
Hey, thanks for your help! I've got a tiny little feature I'm adding to OSV and then I'll most likely go ahead and release this today or tomorrow.

**Comment by PersonTheCat** [comment] 2022-02-01 01:36
Hey, @hzt-plays. It's been a few days, so I'm gonna go ahead and mark this as resolved. If you try out 7.6 (make sure to use CatLib 1.15), let me know if you're still having issues and I'll try to work out something a bit more thorough.

**Closed by PersonTheCat** 2022-02-01 01:36 UTC
